### ISSUE TITLE
Unable to complete install on Catalina 10.15.2

### ISSUE THREAD

**Issue by jeperkins4** [pfnet-research/homebrew-menoh#1] opened 2019-12-22 16:37 UTC
```
==> cmake . -DENABLE_EXAMPLE=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
==> make install
Last 15 lines from /Users/jperkins/Library/Logs/Homebrew/menoh/02.make:
[ 71%] Building CXX object external/onnx/CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
cd /tmp/menoh-20191222-28915-1pypm8y/external/onnx && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DONNX_NAMESPACE=onnx -I/tmp/menoh-20191222-28915-1pypm8y -I/tmp/menoh-20191222-28915-1pypm8y/include -I/tmp/menoh-20191222-28915-1pypm8y/external/onnx  -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIC   -std=gnu++11 -o CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o -c /tmp/menoh-20191222-28915-1pypm8y/external/onnx/onnx/shape_inference/implementation.cc
[ 72%] Building CXX object external/onnx/CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
cd /tmp/menoh-20191222-28915-1pypm8y/external/onnx && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DONNX_NAMESPACE=onnx -I/tmp/menoh-20191222-28915-1pypm8y -I/tmp/menoh-20191222-28915-1pypm8y/include -I/tmp/menoh-20191222-28915-1pypm8y/external/onnx  -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIC   -std=gnu++11 -o CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o -c /tmp/menoh-20191222-28915-1pypm8y/external/onnx/onnx/version_converter/convert.cc
[ 73%] Building CXX object external/onnx/CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
cd /tmp/menoh-20191222-28915-1pypm8y/external/onnx && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DONNX_NAMESPACE=onnx -I/tmp/menoh-20191222-28915-1pypm8y -I/tmp/menoh-20191222-28915-1pypm8y/include -I/tmp/menoh-20191222-28915-1pypm8y/external/onnx  -O2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIC   -std=gnu++11 -o CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o -c /tmp/menoh-20191222-28915-1pypm8y/external/onnx/onnx/version_converter/helper.cc
[ 75%] Linking CXX static library libonnx.a
cd /tmp/menoh-20191222-28915-1pypm8y/external/onnx && /usr/local/Cellar/cmake/3.16.1/bin/cmake -P CMakeFiles/onnx.dir/cmake_clean_target.cmake
cd /tmp/menoh-20191222-28915-1pypm8y/external/onnx && /usr/local/Cellar/cmake/3.16.1/bin/cmake -E cmake_link_script CMakeFiles/onnx.dir/link.txt --verbose=1
/usr/bin/ar qc libonnx.a  CMakeFiles/onnx.dir/onnx/checker.cc.o CMakeFiles/onnx.dir/onnx/common/assertions.cc.o CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o CMakeFiles/onnx.dir/onnx/common/status.cc.o CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o CMakeFiles/onnx.dir/onnx/defs/experiments/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/experiments/experiments_functions.cc.o CMakeFiles/onnx.dir/onnx/defs/function.cc.o CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o CMakeFiles/onnx.dir/onnx/defs/schema.cc.o CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o CMakeFiles/onnx.dir/onnx/optimizer/optimize.cc.o CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libonnx.a(defs.cc.o) has no symbols
/usr/bin/ranlib libonnx.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libonnx.a(defs.cc.o) has no symbols
[ 75%] Built target onnx
make: *** [all] Error 2
```

**Comment by msakai** [comment] 2021-05-06 13:29
Sorry, I overlooked the issue.

I just updated the formula by #3 and GitHub Actions successfully built a bottle for Catalina.
I could not figure out the cause of the problem, but I hope it is now fixed.

**Closed as completed by msakai** 2021-05-06 13:29 UTC
